# Generated by Django 5.1.1 on 2024-10-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField(unique=True)),
                ('empName', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('empDept', models.CharField(choices=[('IT', 'IT'), ('BPS', 'BPS'), ('LEGAL', 'Legal'), ('ADMIN', 'Admin')], default='', max_length=50)),
                ('empAddress', models.TextField()),
            ],
        ),
    ]
